# -*- coding: utf-8 -*-
"""
Created on Tue Jan 22 17:26:25 2019

@author: 2624224
"""
import os
import subprocess
import pickle
import operator
import argparse
import random
import shutil

import file_utils

def generate_octree_list(root_dir, octree_dir, batch_name, num):
    test_octree_list_path = root_dir + '/test_octree_list.txt'
    with open(test_octree_list_path) as file:
        lines = [line.split('_')[0] + '_6_2_000.octree\n' for line in file.readlines()]
    octree_list = list(set(lines))
    
    random.seed()
    random.shuffle(octree_list)

    octree_list_path = root_dir + '/' + batch_name + '_list/octree_list.txt'
    with open(octree_list_path, 'w') as file:
        file.writelines(octree_list[:num])

def generate_lmdb(caffe_root, data_root, octree_dir, batch_name):
    lmdb_dir = data_root + '/' + batch_name + '_lmdb'
    if os.path.exists(lmdb_dir):
        shutil.rmtree(lmdb_dir)

    octree_list = data_root + '/' + batch_name + '_list/octree_list.txt'
    convert_octree_data = caffe_root + '/build/tools/Release/convert_octree_data.exe'
    subprocess.check_call([convert_octree_data, octree_dir, octree_list, lmdb_dir])


def generate_label_files(root_dir, octree_dir, batch_name):
    list_dir = root_dir + '/' + batch_name + '_list/'
    octree_list_path = list_dir + 'octree_list_shuffle.txt'
    with open(octree_list_path) as file:
        lines = file.readlines()

    feature_dir = root_dir + '/' + batch_name + '_feature/'
    labels_paths = file_utils.file_paths_from_dir(feature_dir)

    points_dir = root_dir + '/points/'
    shape_dir = root_dir + '/shape/'
    for i in range(len(lines)):
        shape_name = lines[i].split('_')[0]

        labels_path = labels_paths[2 * i + 1]
        print(labels_path)
        labels = file_utils.labels_from_file(labels_path)

        label_index_path = octree_dir + shape_name + '.label_index'
        print(label_index_path)
        label_index = file_utils.label_index_from_file(label_index_path)

        points_predicted = [labels[index] for index in label_index]
        points_predicted_path = points_dir + shape_name + '.points_predicted'
        print(points_predicted_path)
        with open(points_predicted_path, 'wb') as f:
            pickle.dump(points_predicted, f)

    # to be debugged
        face_index_path = points_dir + shape_name + '.face_index'
        with open(face_index_path, 'rb') as f:
            face_index = pickle.load(f)

        face_label_map = {}
        for i in range(len(points_predicted)):
            fid = face_index[i]
            label = points_predicted[i]
            if fid not in face_label_map:
                face_label_map[fid] = {label:1}
            else:
                if label in face_label_map[fid]:
                    face_label_map[fid][label] += 1
                else:
                    face_label_map[fid][label] = 1

        face_predicted = [max(face_label_map[key].items(),
                              key=operator.itemgetter(1))[0] for key in sorted(face_label_map.keys())]
        face_predicted_path = shape_dir + shape_name + '.face_predicted'
        with open(face_predicted_path, 'wb') as f:
            pickle.dump(face_predicted, f)


# modify prototxt specified by --model: data source; num_output of deconv2_ip layer
# set --weights to the right trained caffemoddel
# set --iterations to the number of models to be tested


if __name__ == '__main__':
    '''
    input:
        cafferoot, top dir of caffe

        rootdir, dir containig shape dir, points dir, and octree dir, dirs and
        files therein must exist

        batchname, the name of this test, used to name list_dir, feature dir
        and lmdb dir

        num, number of shapes to sample for test

    output:
        list dir, feature dir and lmdb dir under rootdir with names batchname_list,
        batchname_feature, batchname_lmdb

        octree_list.txt in list dir, each entry is a name of the octree sampled
        octree_list_shuffle.txt in list dir, generated by convert_octree_data

        dadtabase file in lmdb dir
        
        label_predicted files and label_groundtruth files in feature dir, 
        generated by caffe test
        
        *.points_predicted in points dir
        
        *.face_predicted in shape dir
    '''
    PARSER = argparse.ArgumentParser()
    PARSER.add_argument('--cafferoot',
                        '-c',
                        type=str,
                        required=True)
    PARSER.add_argument('--rootdir',
                        '-r',
                        type=str,
                        help='root dir containning the shape dir, points dir, \
                        octree dir, lmdb dir, feature dir, and list dir',
                    required=True)
    PARSER.add_argument('--batchname',
                        '-b',
                        type=str,
                        help='category name of the dataset, used to name other dirs',
                        required=False,
                        default='')
    PARSER.add_argument('--num',
                        '-n',
                        type=int,
                        help='number of shapes to generate',
                        required=False,
                        default=1)
    ARGS = PARSER.parse_args()

    octree_dir = ARGS.rootdir + '/octree_6_1/'
    
    list_dir = ARGS.rootdir + '/' + ARGS.batchname + '_list/'
    if not os.path.exists(list_dir):
        os.mkdir(list_dir)

    generate_octree_list(ARGS.rootdir, octree_dir, ARGS.batchname, ARGS.num)

    generate_lmdb(ARGS.cafferoot, ARGS.rootdir, octree_dir, ARGS.batchname)

    feature_dir = ARGS.rootdir + '/' + ARGS.batchname + '_feature/'
    if not os.path.exists(feature_dir):
        os.mkdir(feature_dir)

    blob_prefix = '--blob_prefix=' + feature_dir
    model = ARGS.cafferoot + '/examples/o-cnn/segmentation_6_test.prototxt'
    weights = ARGS.cafferoot + '/examples/o-cnn/seg_6_cad.caffemodel'

    caffe = ARGS.cafferoot + '/build/tools/Release/caffe.exe'
    subprocess.check_call([caffe, 'test', '--model=' + model, '--weights=' + weights,
                           '--gpu=0', blob_prefix, '--binary_mode=false', '--save_seperately=true',
                           '--iterations=' + str(ARGS.num)])

    generate_label_files(ARGS.rootdir, octree_dir, ARGS.batchname)
    